#!/bin/bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
. ~/.nvm/nvm.sh
nvm install v12.18.3
npm install -g npm stable
npm install express -g
npm install nodemon -g
npm install pm2 -g
npm install yarn -g
yum install git -y
npm install forever -g
npm install cors -g
#cd /home/ec2-user/monteCards
#rm -rf build
#yarn
#yarn build
#cd ..
#cd /home/ec2-user/sabongexpress
#rm -rf build
#yarn
#yarn build